<img src='https://i.imgur.com/RDAD11M.png' width = '200' align = 'right'>

## *DATA SCIENCE / SECTION 1 / SPRINT 3 / NOTE 1*

# 📝 Assignment

## 1. Portfolio

`Dot product` & `Matrix Multiplication` 을 이용하여 다음 포트폴리오의 사람별 총합을 계산하세요.
- 결과는 `res`에 list형태로 저장합니다.

|People|Name|Price|Amount|
|:-:|:-:|:-:|:-:|
|X|A|100|35|
|X|B|500|10|
|X|C|250|25|
|X|D|50|40|
|Y|A|100|-|
|Y|B|500|50|
|Y|C|250|50|
|Y|D|50|-|
|Z|A|100|-|
|Z|B|500|-|
|Z|C|250|100|
|Z|D|50|-|



In [2]:
# 이곳에 답안을 작성하시기 바랍니다
# 데이터 프레임 생성
import pandas as pd

df = pd.DataFrame([['X','A',100,35],
['X','B',500,10],
['X','C',250,25],
['X','D',50,40],
['Y','A',100,0],
['Y','B',500,50],
['Y','C',250,50],
['Y','D',50,0],
['Z','A',100,0],
['Z','B',500,0],
['Z','C',250,100],
['Z','D',50,0]], columns = ['People', 'Name', 'Price', 'Amount'])
df

People Name  Price  Amount
0       X    A    100      35
1       X    B    500      10
2       X    C    250      25
3       X    D     50      40
4       Y    A    100       0
5       Y    B    500      50
6       Y    C    250      50
7       Y    D     50       0
8       Z    A    100       0
9       Z    B    500       0
10      Z    C    250     100
11      Z    D     50       0

In [3]:
# 가격과 사람별 주식 수 분리
Price = [100, 500, 250, 50]
X = df[df['People'] == 'X']['Amount'].tolist()
Y = df[df['People'] == 'Y']['Amount'].tolist()
Z = df[df['People'] == 'Z']['Amount'].tolist()
print('{} = X,\n\n{} = Y,\n\n{} = Z'.format(X, Y, Z))

[35, 10, 25, 40] = X,

[0, 50, 50, 0] = Y,

[0, 0, 100, 0] = Z


In [4]:
# Dot product (내적 곱) 를 사용하여 res에 저장
import numpy as np

res = [np.dot(X, Price), np.dot(Y, Price), np.dot(Z, Price)]
print('np.dot(A,B) = [X, Y, Z] =', res)

np.dot(A,B) = [X, Y, Z] = [16750, 37500, 25000]


In [40]:
# Matrix Multiplication (행렬 곱) 로 계산 하는 법
import numpy as np

print('np.matmul(A,B) =', [np.matmul(X, Price), np.matmul(Y, Price), np.matmul(Z, Price)])

# @ 로도 행렬 곱이 가능 하지만 array 형태로 있어야 한다. list 일 경우 error 생김.
print('A @ B =', [np.array(X) @ np.array(Price), np.array(Y) @ np.array(Price), np.array(Z) @ np.array(Price)])

np.matmul(A,B) = [16750, 37500, 25000]
A @ B = [16750, 37500, 25000]


In [15]:
# np 곱, 합으로 푸는 방법
print('sum(np.array(A)*np.array(B)) =',[sum(np.array(X) * np.array(Price)), sum(np.array(Y) * np.array(Price)), sum(np.array(Z) * np.array(Price))])

sum(np.array(A)*np.array(B)) = [16750, 37500, 25000]


In [37]:
# 데이터 프레임을 변형해서 계산.
# Money라는 열 하나 추가
df['Money'] = df.Price * df.Amount
df

People Name  Price  Amount  Money
0       X    A    100      35   3500
1       X    B    500      10   5000
2       X    C    250      25   6250
3       X    D     50      40   2000
4       Y    A    100       0      0
5       Y    B    500      50  25000
6       Y    C    250      50  12500
7       Y    D     50       0      0
8       Z    A    100       0      0
9       Z    B    500       0      0
10      Z    C    250     100  25000
11      Z    D     50       0      0

In [38]:
# People로 그룹 한뒤, Money 열의 총합을 계산
df.groupby('People').agg({'Money':['sum']})

Money
          sum
People       
X       16750
Y       37500
Z       25000

## 2. Norms

주어진 값 $x_0, x_1, ... x_n$ 를 element로 갖는 벡터 $v$에 대하여 

$L_1$ Norm 의 정의는 다음과 같습니다. 

$|v| = |x_0| + |x_1| + ... + |x_n|$

$L_2$ Norm 의 정의는 다음과 같습니다.

$||v|| = \sqrt {{x_0}^2 + {x_1}^2 + ... + {x_n}^2}$

이를 참조하여 주어진 벡터에 대해서 $L_2$ Norm 의 값과 $L_1$ Norm 의 값의 차이(**절대값**)를 계산하는 함수를 만드세요.



In [42]:
v = np.array([1, 2, 3, 4])
# |L2 Norm - L1 Norm| 계산 함수
def NormDif(v): # v = np.array()
  L1_norm = np.linalg.norm(v, axis=0, ord=1)
  L2_norm = np.linalg.norm(v, axis=0, ord=2)
  return abs(L2_norm - L1_norm)
NormDif(v)

4.522774424948339

In [43]:
# np.linalg.norm 안쓰고
def NormDif_ori(v):
  L1_norm_ori = sum(abs(v))
  L2_norm_ori = sum(abs(v)**2)**0.5
  return abs(L2_norm_ori - L1_norm_ori)
NormDif_ori(v)

4.522774424948339

## 3. Errors



- 2개의 벡터와, error의 타입을 입력받아 그 결과값을 계산하는 함수를 작성하세요.

- 여기서 error의 타입은 `MSE`, `MAE` 2가지 입니다.



In [62]:
# MSE, MAE error 타입별 계산
def error(x, y, type) :
  # MAE : (실제 값과 예측 값의 차이) error를 절대값으로 변환해 평균화, 이상치가 많을 때, error에 따른 손실이 선형적으로 올라 갈 때
  if type == 'MAE':
    from sklearn.metrics import mean_absolute_error
    return mean_absolute_error(x, y)
  # MSE : (실제 값과 예측 값의 차이) error를 제곱해 평균화, 특이값이 존재할 때 수치가 많이 올라감.
  elif type == 'MSE':
    from sklearn.metrics import mean_squared_error 
    return mean_squared_error(x, y)

# 4. Inverse

- 주어진 matrix에 대해서 inverse matrix를 계산하여 반환하는 함수를 작성하세요. 
- 이 때 inverse 계산이 불가능 한 경우 `-1` 을 반환합니다.

In [70]:
# Inverse matrix 반환 함수
def myInverse(m) : # m = np.array()
  # 행렬식 = determinant
  import numpy as np
  det = np.linalg.det(m)
  if det == 0:
    return -1
  else:
    return np.linalg.inv(m)

In [42]:
min(res)

16750

In [54]:
round(NormDif(np.array([1, 2, 3, 4])), 3)

4.523

In [64]:
round(error(np.array([5, 10, 30]), np.array([21, 2, 8]), 'MSE'), 3)

268.0

In [71]:
myInverse(np.array([[2,4],[4,8]]))

-1

# 🔥 도전과제 



다음 링크의 내용을 참조하여 **Cramer's rule**을 사용해 $x_1$, $x_2$, $x_3$의 값을 구하세요.

<https://youtu.be/6StS7VjtuGI>


$x_1$ + $2x_3$ = 6

$-3x_1$ + $4x_2$ + $6x3$ = 30

$-x_1$ $-2x_2$ + $3x_3$ = 8



In [94]:
import numpy as np

A = np.array([[1,0,2],
              [-3,4,6],
              [-1,-2,3]])

B = np.array([6, 30, 8])

x = np.linalg.solve(A, B)
print('x1 = {}, x2 = {}, x3 = {}'.format(x[0],x[1],x[2]))

x1 = -0.9090909090909104, x2 = 1.636363636363636, x3 = 3.454545454545454


In [91]:
# Cramer's rule 사용해서 직접 풀어보기
# x1, x2, x3 를 구하기 위해서는 D, Dx1, Dx2, Dx3를 구해야 한다.
# x1 = Dx1/D
# x2 = Dx2/D
# x3 = Dx3/D

In [92]:
# D(행렬식) 구하기.
D = np.linalg.det(A)
D

44.000000000000014

In [111]:
# Dx1, Dx2, Dx3 구하려면 A 행렬에 B 값을 x1, x2, x3 위치에 넣어서 행렬식을 구해야 한다.
# A 행렬에 x1, x2, x3 넣기
Ax1 = np.insert(np.delete(A, 0, axis = 1), 0, B, axis = 1)
Ax2 = np.insert(np.delete(A, 1, axis = 1), 1, B, axis = 1)
Ax3 = np.insert(np.delete(A, 2, axis = 1), 2, B, axis = 1)
print('{} = Ax1,\n\n{} = Ax2,\n\n{} = Ax3'.format(Ax1, Ax2, Ax3))

[[ 6  0  2]
 [30  4  6]
 [ 8 -2  3]] = Ax1,

[[ 1  6  2]
 [-3 30  6]
 [-1  8  3]] = Ax2,

[[ 1  0  6]
 [-3  4 30]
 [-1 -2  8]] = Ax3


In [108]:
# Dx1, Dx2, Dx3 구하기
Dx1 = np.linalg.det(Ax1)
Dx2 = np.linalg.det(Ax2)
Dx3 = np.linalg.det(Ax3)
print('Dx1 = {}, Dx2 = {}, Dx3 = {}'.format(Dx1, Dx2, Dx3))

Dx1 = -40.0, Dx2 = 72.0, Dx3 = 152.0


In [110]:
# x1, x2, x3 구하기
x1 = Dx1/D
x2 = Dx2/D
x3 = Dx3/D
print('x1 = {}, x2 = {}, x3 = {}'.format(x1, x2, x3))

x1 = -0.9090909090909088, x2 = 1.6363636363636358, x3 = 3.4545454545454533
